### ISSUE TITLE
stride and shape shoudl be factorized via kwk::prefilled_array

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/kiwaku#44]
## Tasks:
 - [x] Split`detail/shaper.hpp`into the detail and non-detail parts
 - [x] Implements `kwk::prefilled_array<Type, Desc>`
 - [x] Rewrite `kwk::shape` with  `kwk::prefilled_array`
 - [x] Rewrite `kwk::stride` with  `kwk::prefilled_array`
 - [x] Fix #41 
 - [x] Fix #40

**Comment by jfalcou** [comment]
Fixed in #50
